# Generated by Django 4.2.5 on 2023-09-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contact',
            field=models.CharField(blank=True, default='7481009993', max_length=13),
        ),
        migrations.AddField(
            model_name='appointment',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
