# Generated by Django 4.2.5 on 2023-09-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appointment_age_appointment_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.CharField(blank=True, default='as', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='contact',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
