# Generated by Django 4.2.5 on 2023-09-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_appointment_symptoms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='medicine',
            new_name='advice',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='problem',
            new_name='symptoms',
        ),
        migrations.AddField(
            model_name='patient',
            name='rx',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
