# Generated by Django 4.2.5 on 2023-09-21 11:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_patient_advice_alter_patient_rx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_id_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='appointment_id', unique=True),
        ),
    ]
