# Generated by Django 4.2.5 on 2023-09-21 11:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='email', unique_with=['first_name', 'last_name']),
        ),
    ]
