# Generated by Django 4.2.5 on 2023-09-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_patient_patient_id_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_id_slug',
        ),
        migrations.AddField(
            model_name='appointment',
            name='meet_link',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
