# Generated by Django 4.2.5 on 2023-09-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_patient_patient_id_slug_appointment_meet_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='predicted_file',
            field=models.FileField(default=None, max_length=250, upload_to='predicted_diagnosis/'),
        ),
    ]
