# Generated by Django 4.2.5 on 2023-09-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_appointment_predicted_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='predicted_file',
            field=models.FileField(blank=True, default=None, max_length=250, upload_to='predicted_diagnosis/'),
        ),
    ]
