# Generated by Django 4.2.5 on 2023-09-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_appointment_predicted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='offline', max_length=20),
        ),
    ]
