# Generated by Django 4.2.5 on 2023-09-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appointment_symptoms_alter_appointment_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='blood_group',
            field=models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'O+'), ('6', 'O-')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], default='1', max_length=20),
        ),
    ]
