# Generated by Django 4.2.5 on 2023-09-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appointment_blood_group_appointment_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='predicted_diagnosis',
        ),
        migrations.AddField(
            model_name='appointment',
            name='predicted_file',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='predicted_diagnosis/'),
        ),
    ]
