# Generated by Django 4.2.5 on 2023-09-21 11:07

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_appointment_appointment_id_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='patient_id', unique=True),
        ),
    ]
