# Generated by Django 4.2.5 on 2023-09-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_patient_patient_id_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='blood_group',
            field=models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'O+'), ('6', 'O-')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='1', max_length=20),
        ),
    ]
