# Generated by Django 4.2.5 on 2023-09-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_appointment_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meet_link',
            field=models.CharField(blank=True, default='none', max_length=255),
        ),
    ]
