# Generated by Django 4.2.4 on 2023-09-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='relation',
            field=models.CharField(choices=[('1', 'Self'), ('2', 'Father'), ('3', 'Mother'), ('4', 'Wife'), ('5', 'Husband'), ('6', 'Son'), ('7', 'Daughter'), ('8', 'Brother')], default='1', max_length=20),
        ),
    ]
