# Generated by Django 4.2.4 on 2023-09-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
    ]
